name: Comment release labels on PRs

on:
  pull_request:
    types: [opened]

jobs:
  check_pr_label_and_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: github-actions-up-and-running/pr-comment@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Message to comment
          message: |
            Please add one of the following labels to this pull request to indicate the version bump it should result in:
            - release/major
            - release/minor
            - release/patch
            - release/prerelease

            If no label is added a prerelease version bump is assumed.
